### PR TITLE
PetAdoptation page

### PR DESCRIPTION
**Pull request by Abdul-Azeez060**
Added PetAdoptation webpage

### CODE REVIEW

**Comment by TammyAlok2** [comment]
Have you made a folder inside project section if not made a project with your name

**Comment by Abdul-Azeez060** [comment]
yes inside projects folder I made another folder by username-projectname and inside that this html and css code is present

**Comment by TammyAlok2** [comment]
make sure to star the repo 
congratulation your pr is successfully merged

**Comment by Abdul-Azeez060** [comment]
sure thank you

**Comment by TammyAlok2** [comment]
Have you got hacktoberfest first batch

**Comment by Abdul-Azeez060** [comment]
I think so no, but in hactoberfest website it I giving waiting time of 7 days, I am first time taking part in hactoberfest.

**Pull request merged**
