### PR TITLE
Create login.html

### PR DESCRIPTION
**Pull request by Pritee-gupta-jpg**

### CODE REVIEW

**Comment by sammyifelse** [comment]
please assign this issue to me
i can create a beautiful login page for the website

**Comment by Bib3k4u** [comment]
Is it still open? Can I work on this?

**Comment by TammyAlok2** [comment]
Yes @Pritee-gupta-jpg  you can work

**Comment by Pritee-gupta-jpg** [comment]
Please merge my PR and kindly add hactoberfest-accepted label. Thank you

**Pull request closed without merging**
