### PR TITLE
Digital Clock - HacktoberFest2023

### PR DESCRIPTION
**Pull request by pg00019**
Digital Clock -> using HTML , CSS , Javascript

### CODE REVIEW

**Comment by Vanshika2103** [comment]
Please assign this task to me for creating a digital clock using html, css and js.

**Comment by TammyAlok2** [comment]
Congratulation your pr is successfully merged make sure to star the repo
kindly help me by registering yourself in mood indigo
Link : https://my.moodi.org/
referal code : CCP62216
make sure to share with freinds as well
comment after doing

**Comment by Vanshika2103** [comment]
Please check out my github react clock repo i have made this using html css
ReactJs. And please update me if you like my this design.

**Comment by Vanshika2103** [comment]
https://codesandbox.io/p/github/Vanshika2103/Reactclock

This is the link of digital clock using html css and basic react js

**Comment by Vanshika2103** [comment]
If you like this then merge otherwise let me know and i will design
another one for you.
Thank you

**Pull request merged**
